export const demoMarkets = [
  {
    id: "usdc-base",
    symbol: "USDC",
    name: "USDC Base Liquidity",
    category: "Digital cash",
    protocol: "Arc reference market",
    network: "Arc",
    liquidityUsd: 18_400_000,
    utilizationPct: 64,
    apyPct: 4.8,
    collateralVolatilityPct: 1,
    oracleCount: 2,
    contractStatus: "allowlisted",
    ageMinutes: 2,
    completenessPct: 100,
    source: "Demonstration dataset",
    sourceUrl: "https://explorer.arc.io",
    address: "Pending live adapter",
    observedAt: "Demo snapshot",
    note: "Stablecoin liquidity baseline for policy calibration.",
    dataMode: "demo"
  },
  {
    id: "rwa-fund",
    symbol: "RWA",
    name: "Tokenized Treasury Fund",
    category: "Tokenized RWA",
    protocol: "Arc reference market",
    network: "Arc",
    liquidityUsd: 6_750_000,
    utilizationPct: 76,
    apyPct: 5.35,
    collateralVolatilityPct: 3,
    oracleCount: 1,
    contractStatus: "review",
    ageMinutes: 7,
    completenessPct: 92,
    source: "Demonstration dataset",
    sourceUrl: "https://explorer.arc.io",
    address: "Pending live adapter",
    observedAt: "Demo snapshot",
    note: "Representative RWA case; issuer and transfer restrictions require human review.",
    dataMode: "demo"
  },
  {
    id: "cirbtc-growth",
    symbol: "cirBTC",
    name: "cirBTC Growth Market",
    category: "Crypto collateral",
    protocol: "Arc reference market",
    network: "Arc",
    liquidityUsd: 2_150_000,
    utilizationPct: 91,
    apyPct: 12.4,
    collateralVolatilityPct: 68,
    oracleCount: 1,
    contractStatus: "allowlisted",
    ageMinutes: 19,
    completenessPct: 100,
    source: "Demonstration dataset",
    sourceUrl: "https://explorer.arc.io",
    address: "Pending live adapter",
    observedAt: "Demo snapshot",
    note: "High utilization and volatile collateral trigger protective limits.",
    dataMode: "demo"
  }
];

export const markets = demoMarkets;
